name: Guide 4 Regular Guy
favicon: null
layout_spectrum: 0.5647095448803157
typography_spectrum: 0.9570883028209209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8259437619708478
  lightness: 0.7231610452290624
  saturation: 0.5291306036524475
  rhythmicContrast: 0.9763757584150881
purpose: []
